BMR16 Login screen
AmaliTech-Training-Rw/Meeting-Room-booking-App pull request #11
Opened 2023-05-24 15:58 UTC by kamdaou-amalitech

Created login screen, the ViewModel, and tests.
Test written
Email and password validation

2023-05-25 14:36 UTC, bensek commented on ui/authentication/build.gradle.kts
> +    "implementation"(Lifecycle.composeLifecycle)
This doesn't look fixed. Removed the lifecycle from here.

2023-05-25 14:39 UTC, kamdaou-amalitech commented on ui/authentication/build.gradle.kts
> +    "implementation"(Lifecycle.composeLifecycle)
I use that dependency in LoginScreen, line 62. If I remove it, I will not be able to access collectAsStateWithLifecycle.

2023-05-25 14:41 UTC, bensek commented on ui/authentication/build.gradle.kts
> +    "implementation"(Lifecycle.composeLifecycle)
Add it to the base compose file other features need it too.

2023-05-25 15:08 UTC, bensek approved these changes

2023-05-26 06:27 UTC, bensek requested changes

2023-05-26 06:27 UTC, bensek commented on app/build.gradle.kts
> +    implementation(project(Modules.uiAuthentication))
Cadet, Login, SignUp,Forgot Password are all supposed to be part of the onboarding module. It shouldnt be a separate module. It's all the same feature.

2023-05-26 07:41 UTC, esthcarelle approved these changes

2023-05-26 12:57 UTC, bensek approved these changes

2023-05-26 13:22 UTC, merged