Drawer
AmaliTech-Training-Rw/Meeting-Room-booking-App pull request #14
Opened 2023-05-26 12:34 UTC by ma-za-kpe

2023-05-27 10:04 UTC, esthcarelle commented
Could you change the colors and match figma?

2023-05-27 10:10 UTC, ma-za-kpe commented
> Could you change the colors and match figma?

the colors are what is in the develop branch. When I was setting up modularisation, I added all the colors, but now they are not present. What do you suggest?

2023-05-27 10:12 UTC, ma-za-kpe commented
Also, my phone is in dark mode. So that's the dark mode version of the app.

2023-05-27 10:15 UTC, esthcarelle commented
@ma-za-kpe can you check with the colors Cadet has been using for the login screen?

2023-05-28 20:58 UTC, ma-za-kpe commented
> @ma-za-kpe can you check with the colors Cadet has been using for the login screen?

I've used the colors as seen in the drawer... however, colors need to be separated otherwise there is no need to have both themes in the Theme.kt file.

2023-05-28 21:13 UTC, esthcarelle commented on app/src/main/java/com/amalitech/bookmeetingroom/MainActivity.kt
>  }
Before we merge this could you remove both the LoginScreen call in mainActivity and BookMeetingRoomDrawer(appState)

2023-05-28 21:13 UTC, esthcarelle commented on core_ui/src/main/java/com/amalitech/core_ui/ui/BookMeetingRoomDrawer.kt
> +
Could you exctract this  val drawerItems = mapOf(
        Pair("Home", Icons.Default.Home),
        Pair("Booking Requests", Icons.Default.Bookmarks),
        Pair("Users", Icons.Default.People),
        Pair("Rooms", Icons.Default.Room),
        Pair("Booking History", Icons.Default.History),
        Pair("Profile", Icons.Default.PersonOutline),
        Pair("Dashboard", Icons.Default.Dashboard),
        Pair("Logout", Icons.Default.Home)
    ) in a sealed class?

2023-05-28 21:13 UTC, esthcarelle commented on core_ui/src/main/java/com/amalitech/core_ui/ui/BookMeetingRoomTopAppBar.kt
> +fun BookMeetingRoomTopAppBar(
We re not supposed to have this top app bar in this branch

2023-05-28 21:13 UTC, esthcarelle commented on core_ui/src/main/java/com/amalitech/core_ui/ui/BookMeetingRoomTopAppBar.kt
> +fun BookMeetingRoomTopAppBar(
There is a separate ticket for that

2023-05-28 21:13 UTC, esthcarelle commented on core_ui/src/main/java/com/amalitech/core_ui/util/snackbar/SnackbarManager.kt
> +}
Why do we have a snack bar manager in this branch?

2023-05-28 21:15 UTC, ma-za-kpe commented on app/src/main/java/com/amalitech/bookmeetingroom/MainActivity.kt
>  }
Done

2023-05-28 21:18 UTC, ma-za-kpe commented on core_ui/src/main/java/com/amalitech/core_ui/ui/BookMeetingRoomTopAppBar.kt
> +fun BookMeetingRoomTopAppBar(
Ive remove the top bar. PTAL

2023-05-28 21:18 UTC, ma-za-kpe commented on core_ui/src/main/java/com/amalitech/core_ui/util/snackbar/SnackbarManager.kt
> +}
It remove repeation of snackbar logic and the need to check for nullability

2023-05-29 09:48 UTC, ma-za-kpe commented on core_ui/src/main/java/com/amalitech/core_ui/util/snackbar/SnackbarManager.kt
> +}
Hi @esthcarelle ... Its removed, PTAL

2023-05-29 10:18 UTC, esthcarelle commented on core_ui/src/main/java/com/amalitech/core_ui/util/snackbar/SnackbarManager.kt
> +}
We can surely have it but I think that has to be in a separate branch, I ll create a ticket for that

2023-05-29 11:25 UTC, ma-za-kpe commented on core_ui/src/main/java/com/amalitech/core_ui/ui/BookMeetingRoomDrawer.kt
> +
Hi @esthcarelle ... Its done, PTAL

2023-05-29 12:36 UTC, esthcarelle approved these changes

2023-05-29 14:15 UTC, bensek commented on core_ui/src/main/java/com/amalitech/core_ui/state/BookMeetingRoomAppState.kt
> +    val assets: AssetManager,
Why are we passing assets and resources? These should be declared in the composable directly.

2023-05-29 14:16 UTC, bensek requested changes
@ma-za-kpe

2023-05-29 15:17 UTC, ma-za-kpe commented on core_ui/src/main/java/com/amalitech/core_ui/domain/TopLevelDestination.kt
> +enum class TopLevelDestination(
to hide the toolbar or bottom bar appropriatly

2023-05-29 15:18 UTC, ma-za-kpe commented on core_ui/src/main/java/com/amalitech/core_ui/state/BookMeetingRoomAppState.kt
> +    val assets: AssetManager,
single source of truth outside of individual contexts. i thought it was a better approach than having them scattered all over the app.

2023-05-29 15:19 UTC, ma-za-kpe commented on core_ui/src/main/java/com/amalitech/core_ui/components/drawer/DraweState.kt
> +sealed class DrawerItem(var title:String, var icon: ImageVector){
Alright.

2023-05-29 15:22 UTC, ma-za-kpe commented on core_ui/src/main/java/com/amalitech/core_ui/components/drawer/BookMeetingRoomDrawer.kt
> +            when (item) {
couldnt we simply move the navigate logic up several layers to have access to what the callback exposes? 

I might not be getting this right.

2023-05-29 16:19 UTC, bensek commented on core_ui/src/main/java/com/amalitech/core_ui/components/drawer/BookMeetingRoomDrawer.kt
> +            when (item) {
Yes that's what I am saying

2023-05-29 16:26 UTC, bensek commented on core_ui/src/main/java/com/amalitech/core_ui/state/BookMeetingRoomAppState.kt
> +    val assets: AssetManager,
For these they already access the ssot which is the compositelocal. Remember your composable params describe it's behavior which is the state specific to this composable and the actions/events nothing else should be added.

2023-05-31 09:09 UTC, ma-za-kpe commented on core_ui/src/main/java/com/amalitech/core_ui/state/BookMeetingRoomAppState.kt
> +    val assets: AssetManager,
Done, PTAL

2023-05-31 09:09 UTC, ma-za-kpe commented on core_ui/src/main/java/com/amalitech/core_ui/components/drawer/DraweState.kt
> +sealed class DrawerItem(var title:String, var icon: ImageVector){
Added, PATL

2023-05-31 09:21 UTC, ma-za-kpe commented on core_ui/src/main/java/com/amalitech/core_ui/components/drawer/BookMeetingRoomDrawer.kt
> +            appState.coroutineScope.launch { appState.drawerState.close() }
DONE, PTAL

2023-05-31 09:29 UTC, ma-za-kpe commented on core_ui/src/main/java/com/amalitech/core_ui/components/drawer/BookMeetingRoomDrawer.kt
> +            when (item) {
PTAL

2023-05-31 12:29 UTC, bensek commented on core_ui/src/main/java/com/amalitech/core_ui/components/drawer/BookMeetingRoomDrawer.kt
> +            when (item) {
We still have the when expression which we don't need

2023-05-31 12:50 UTC, ma-za-kpe commented on core_ui/src/main/java/com/amalitech/core_ui/components/drawer/BookMeetingRoomDrawer.kt
> +            when (item) {
I had a list earlier on, but was told to change to a sealed class...  An example of what you want would be helpful

2023-05-31 12:54 UTC, bensek commented on core_ui/src/main/java/com/amalitech/core_ui/components/drawer/BookMeetingRoomDrawer.kt
> +            when (item) {
Check the BottomNavigationBar implementation in the core_ui module.

2023-05-31 12:54 UTC, bensek commented on core_ui/src/main/java/com/amalitech/core_ui/state/BookMeetingRoomAppState.kt
>      coroutineScope: CoroutineScope = rememberCoroutineScope(),
Are we using it here? Coz I saw you define it in the composable itself.

2023-05-31 14:34 UTC, ma-za-kpe commented on core_ui/src/main/java/com/amalitech/core_ui/state/BookMeetingRoomAppState.kt
>      coroutineScope: CoroutineScope = rememberCoroutineScope(),
It's in a globally accessible location. But you can create one for your own scope if you so wish.

2023-05-31 15:06 UTC, ma-za-kpe commented on core_ui/src/main/java/com/amalitech/core_ui/components/drawer/BookMeetingRoomDrawer.kt
> +            when (item) {
Done, PTAL

2023-06-01 11:05 UTC, kamdaou-amalitech commented on core_ui/src/main/java/com/amalitech/core_ui/components/drawer/BookMeetingRoomDrawer.kt
I think your variable selectedItem will not survive configuration changes, so you need to use rememberSaveable to avoid having its value reset to the initial one when there is a screen rotation, for instance. But I also wonder why we need this variable. Maybe @bensek and @esthcarelle can tell us what they think.

2023-06-01 11:17 UTC, kamdaou-amalitech commented on core_ui/src/main/java/com/amalitech/core_ui/theme/Color.kt
In the drawer design, we only have three colors: white for the background, yellow for the selected item, and black for others. And all of these colors exist in the previous color file. Why do we have to change them with these colors?

2023-06-01 12:50 UTC, kamdaou-amalitech commented on core_ui/src/main/java/com/amalitech/core_ui/theme/Color.kt
Do the generated colors match the colors in the Figma design?

2023-06-01 13:37 UTC, ma-za-kpe commented on core_ui/src/main/java/com/amalitech/core_ui/theme/Color.kt
Yes, they do.

2023-06-01 13:54 UTC, kamdaou-amalitech commented on core_ui/src/main/java/com/amalitech/core_ui/theme/Color.kt
If you say so.

2023-06-01 14:35 UTC, kamdaou-amalitech commented on core_ui/src/main/java/com/amalitech/core_ui/theme/Color.kt
That is why I removed the colors you added to add only the colors we need. And I think 0xFFCC47 should be the primary color because that's the most used in the app. You can try running the entire app with the colors that you've added to see that colors will change drastically. Can you try to call LoginScreen() in the main activity and see the result? Isn't it better that you add the colors you need to the existing ones for the light mode and then create new colors for the dark mode, if you wish?

2023-06-05 08:53 UTC, bensek commented on core_ui/src/main/java/com/amalitech/core_ui/state/BookMeetingRoomAppState.kt
>      coroutineScope: CoroutineScope = rememberCoroutineScope(),
We don't have to define it globally then cause it will lead to memory leaks.

2023-06-05 09:27 UTC, merged