bmr22 forgot password screen
AmaliTech-Training-Rw/Meeting-Room-booking-App pull request #15
Opened 2023-05-26 14:45 UTC by kamdaou-amalitech

Forgot password screen
Tests
Tests done:
![forgot_password_scree](https://github.com/AmaliTech-Training-Rw/Meeting-Room-booking-App/assets/132997531/50e56f37-2724-4191-83d6-6e7bafb22a3d)

- email validation
- email addresses that don't exist in DB
- Correct email address
- SnackBar value set to null once it's shown
- The email address entered by the user is kept in the ViewModel state
- Errors are added to the ViewModel state

2023-05-29 14:57 UTC, bensek approved these changes

2023-05-30 10:32 UTC, esthcarelle requested changes

2023-05-30 10:32 UTC, esthcarelle commented on app/src/main/java/com/amalitech/bookmeetingroom/MainActivity.kt
> +                        onNavigateToHome = { /*TODO*/ })
Could you remove this before it gets merged?

2023-05-30 10:32 UTC, esthcarelle commented on ui/onboarding/src/main/java/com/amalitech/onboarding/forgot_password/ForgotPasswordViewModel.kt
> +
Can you remove every unused space and format codes?

2023-05-30 11:03 UTC, kamdaou-amalitech commented on ui/onboarding/src/main/java/com/amalitech/onboarding/forgot_password/ForgotPasswordViewModel.kt
> +
Check again please

2023-05-31 09:01 UTC, esthcarelle approved these changes

2023-05-31 09:02 UTC, merged