bmr58 Splash screen and navigation
AmaliTech-Training-Rw/Meeting-Room-booking-App pull request #18
Opened 2023-05-30 12:04 UTC by kamdaou-amalitech

Called splash animation in splash screen
Created navigation
Nested navigation will be used in the navigation ticket
Testing this navigation can be tricky, but with code from the navigation ticket, it will be easy.

2023-05-31 16:04 UTC, esthcarelle requested changes

2023-05-31 16:04 UTC, esthcarelle commented on ui/onboarding/src/main/java/com/amalitech/onboarding/OnboardingScreen.kt
>                  }
Why do we have it repeated?

2023-06-01 09:42 UTC, esthcarelle commented
you have conflicts

2023-06-01 09:48 UTC, kamdaou-amalitech commented on app/src/main/java/com/amalitech/bookmeetingroom/MainActivity.kt
> +                val shouldShowOnboarding = sharedPref.loadShouldShowOnboarding()
This code will be replaced with codes from the navigation ticket, so I don't think working on it is efficient. I have done it just because the ticket says that we should show the splash screen.

2023-06-01 09:51 UTC, kamdaou-amalitech commented on ui/onboarding/src/main/java/com/amalitech/onboarding/OnboardingScreen.kt
>                  }
Because even when the user clicks on "enter" if they are using a PC, or on "OnGo" when they are using a phone, we consider it as clicking on the button. It makes it easier for the user to interact with the app. It's also the same thing for the tabulation key. By the way, I have updated a bit this code in the bmr20 ticket

2023-06-01 09:55 UTC, esthcarelle requested changes

2023-06-01 09:55 UTC, esthcarelle commented on app/src/main/java/com/amalitech/bookmeetingroom/MainActivity.kt
> +                        )
Then if this is the other branch, could you remove it?There is no point of having it here

2023-06-01 09:55 UTC, esthcarelle commented on ui/onboarding/src/main/java/com/amalitech/onboarding/splash_screen/SplashScreenUiState.kt
> +    val hasFinishedChecking: Boolean = false,
Why is this UIState a data class?

2023-06-01 10:03 UTC, kamdaou-amalitech commented on app/src/main/java/com/amalitech/bookmeetingroom/MainActivity.kt
> +                        )
That's the problem. I did what you asked in the ticket, even if the description saying that we should show the splash screen right after opening the app should be in the bmr20 ticket description. But I will remove it.

2023-06-01 10:06 UTC, kamdaou-amalitech commented on app/src/main/java/com/amalitech/bookmeetingroom/MainActivity.kt
> +                        )
It's done

2023-06-02 17:46 UTC, bensek approved these changes

2023-06-05 09:28 UTC, esthcarelle commented
Could you please resolve conflicts before I merge this?

2023-06-05 09:38 UTC, kamdaou-amalitech commented
Conflicts are resolved

2023-06-05 10:41 UTC, merged