BMR20 Navigation
AmaliTech-Training-Rw/Meeting-Room-booking-App pull request #19
Opened 2023-06-01 08:51 UTC by kamdaou-amalitech

Added navigations
Renamed functions to match navigation flow
Removed unused codes
Testing can be done by navigating the app

2023-06-02 15:40 UTC, esthcarelle requested changes

2023-06-02 15:40 UTC, esthcarelle commented on app/src/main/java/com/amalitech/bookmeetingroom/MainActivity.kt
>  }
Can you create another file named AppNavigation? and extract the navigation composable to that class?

2023-06-02 15:40 UTC, esthcarelle commented on app/src/main/java/com/amalitech/bookmeetingroom/MainActivity.kt
> +            }
This Scaffold should be in another composable, you should create another file for the NavHost

2023-06-02 17:37 UTC, bensek requested changes

2023-06-02 17:37 UTC, bensek commented on app/src/main/java/com/amalitech/bookmeetingroom/MainActivity.kt
> +                val shouldShowOnboarding = sharedPref.loadShouldShowOnboarding()
Create a MainViewModel tied to the MainActivity that will hold state for the navigation and global information that can be shared across the entire application. Inject the sharedpreferences from there and expose a state called showOnboarding.

2023-06-05 09:15 UTC, kamdaou-amalitech commented on app/src/main/java/com/amalitech/bookmeetingroom/MainActivity.kt
> +                val shouldShowOnboarding = sharedPref.loadShouldShowOnboarding()
The ViewModel is created

2023-06-05 09:29 UTC, bensek approved these changes

2023-06-05 12:22 UTC, esthcarelle commented
Conflicts

2023-06-07 08:46 UTC, merged