Ft bmr29 claude
AmaliTech-Training-Rw/Meeting-Room-booking-App pull request #24
Opened 2023-06-03 14:13 UTC by kclaudeeager

2023-06-05 08:38 UTC, esthcarelle requested changes

2023-06-05 08:38 UTC, esthcarelle commented on app/src/main/java/com/amalitech/bookmeetingroom/MainActivity.kt
> +
Why did you call the Login Screen please?

2023-06-05 08:38 UTC, esthcarelle commented on ui/rooms/src/main/java/com/amalitech/rooms/RoomScreen.kt
> +    val spacing = LocalSpacing.current
Can you pass the view model as argument and add a mocked Listed of Rooms?

2023-06-05 08:38 UTC, esthcarelle commented on ui/swipe_animation/src/main/java/com/amalitech/swipe_animation/components/SwipeableCard.kt
> +fun SwipeableCard(
This should be in another ticket, another branch, I understand that it s not yet merged but after merging the other ticket , this should be removed from this branch

2023-06-05 08:38 UTC, esthcarelle commented on ui/rooms/src/main/java/com/amalitech/rooms/components/Room.kt
> +    roomName: String,
COuld you pass the roomName,numberOfPeople and roomFeatures in a data class

2023-06-07 20:16 UTC, esthcarelle commented
conflicts please

2023-06-09 12:43 UTC, esthcarelle requested changes

2023-06-09 12:43 UTC, esthcarelle commented on ui/rooms/proguard-rules.pro
> +# You can control the set of applied configuration files using the
It looks like the proguard files are present here now

2023-06-15 08:54 UTC, kamdaou-amalitech requested changes

2023-06-15 08:54 UTC, kamdaou-amalitech commented on app/src/main/java/com/amalitech/bookmeetingroom/BookMeetingApplication.kt
> -                appModule
Removing the app module will make the app crashes when there is an instantiation of the MainViewModel class

2023-06-15 08:54 UTC, kamdaou-amalitech commented on ui/swipe_animation/src/main/java/com/amalitech/swipe_animation/SwipeableCardSideContents.kt
> +    val swipeDirection = remember { mutableStateOf(SwipeDirection.None) }
Can you use rememberSaveable instead of remember, as remember will not keep values on configuration change?

2023-06-15 08:54 UTC, kamdaou-amalitech commented on ui/swipe_animation/src/main/java/com/amalitech/swipe_animation/SwipeableCardSideContents.kt
> +    var isLeftContentVisible by remember { mutableStateOf(isLeftVisible) }
Instead of creating another variable, can we use the isLeftVisible param? And when the function will be called, we will provide a mutable state to it. The same thing for isRightVisible

2023-06-15 08:54 UTC, kamdaou-amalitech commented on ui/swipe_animation/src/main/java/com/amalitech/swipe_animation/SwipeableCardSideContents.kt
> +        modifier = modifier
All the modifiers are available in a Row composable, so why not use them directly in the Row composable below instead of nesting Card and Box Composable?
Also, with spacing, we have `spaceExtraSmall = 4.dp` and `spaceSmall = 8.dp`, so you can replace these values with values from our LocalSpacing.

2023-06-15 08:54 UTC, kamdaou-amalitech commented on ui/rooms/src/main/java/com/amalitech/rooms/components/Room.kt
> +    Box(
What's the use of having the Box here if it has the same size as the IconButton, and we can change the background of the IconButton too?

2023-06-15 08:54 UTC, kamdaou-amalitech commented on ui/rooms/src/main/java/com/amalitech/rooms/components/Room.kt
> +            .background(Color(0xFFFFCC47))
Can we use colors from MaterialTheme?

2023-06-15 08:54 UTC, kamdaou-amalitech commented on ui/rooms/src/main/java/com/amalitech/rooms/components/Room.kt
> +                        Spacer(modifier = Modifier.height(8.dp))
Can we use LocalSpacing.current.spaceSmall?

2023-06-15 12:12 UTC, bensek requested changes

2023-06-15 12:12 UTC, bensek commented on data/rooms/build.gradle.kts
> +    "implementation"(Retrofit.okHttp)
Remove this from this file and remove the room dependencies as well. They should be added to another gradle file called base_data_module. If it is not there create it.

2023-06-15 12:12 UTC, bensek commented on data/rooms/src/main/java/com/amalitech/rooms/repository/RoomRepositoryImpl.kt
> +        Room(
Indent this correctly

2023-06-15 12:12 UTC, bensek commented on domain/rooms/src/main/java/com/amalitech/rooms/usecase/GetRoomsUseCase.kt
> +    fun execute(): List<Room>{
We are using operator functions called invoke for usecases so that you can call your usecase as a function

2023-06-17 19:46 UTC, esthcarelle requested changes

2023-06-17 19:46 UTC, esthcarelle commented on data/rooms/proguard-rules.pro
> +# hide the original source file name.
could ypu find a way of removing the proguard files please?

2023-06-19 04:59 UTC, kclaudeeager commented on data/rooms/proguard-rules.pro
> +# hide the original source file name.
for every module I created?

2023-07-19 09:56 UTC, kamdaou-amalitech commented
@bensek @esthcarelle I have updated the code and added some functionalities that were not added. Please check if it fulfills your requirements

2023-07-20 10:01 UTC, esthcarelle approved these changes

2023-07-23 20:52 UTC, esthcarelle commented
@kamdaou-amalitech why does the image look like it s cut?

2023-07-24 09:08 UTC, kamdaou-amalitech commented
@esthcarelle it's just rounded into a rounded corner shape as in the design.

2023-07-24 09:14 UTC, esthcarelle commented
@kamdaou-amalitech it has conflicts

2023-07-24 09:18 UTC, esthcarelle commented
the image looks cut and it doesn t look like the mockup https://www.figma.com/file/wxds5xGNdNCOLmY4qV97lo/booking-meeting-room-app?node-id=86%3A2136&mode=dev

2023-07-24 09:23 UTC, kamdaou-amalitech commented
Sorry, I see what you are talking about. Let me fix that

2023-07-24 09:25 UTC, esthcarelle commented
@kamdaou-amalitech the pipeline is not passing

2023-07-24 11:11 UTC, bensek approved these changes

2023-07-24 11:15 UTC, merged