bmr25 Dashboard graph
AmaliTech-Training-Rw/Meeting-Room-booking-App pull request #27
Opened 2023-06-06 07:34 UTC by kamdaou-amalitech

Added dashboard graph and UI components

2023-06-06 07:47 UTC, kamdaou-amalitech commented
![dashboard_graph](https://github.com/AmaliTech-Training-Rw/Meeting-Room-booking-App/assets/132997531/f47b48cb-1118-40ad-abce-aeebb48eb57f)

2023-06-06 07:49 UTC, kamdaou-amalitech commented
https://github.com/AmaliTech-Training-Rw/Meeting-Room-booking-App/assets/132997531/1bacadad-c295-4736-b49c-697df40ba76c

2023-06-06 15:57 UTC, bensek reviewed
I am also wondering why we have to create a bar graph from scratch yet there are already existing libraries for this! Maintaining this might not be easy since there are might be many features that you have to add to make this a real bar.

2023-06-07 20:13 UTC, esthcarelle requested changes

2023-06-07 20:13 UTC, esthcarelle commented on ui/admin/src/main/java/com/amalitech/admin/components/BarGraph.kt
> +    roomNameColor: Color
Are not passing the rooms ,don't we need the rooms to draw the graph?

2023-06-12 09:58 UTC, kamdaou-amalitech commented
https://github.com/AmaliTech-Training-Rw/Meeting-Room-booking-App/assets/132997531/6a8b9013-4a30-4d4e-8402-f84a31c380f9

@bensek can you check the code, please?

2023-06-12 11:27 UTC, esthcarelle requested changes

2023-06-12 11:27 UTC, esthcarelle commented on ui/admin/src/main/res/layout/barchart.xml
> +        android:id="@+id/chart1"
Why do we have an XML file?

2023-06-12 11:49 UTC, kamdaou-amalitech commented on app/src/main/java/com/amalitech/bookmeetingroom/MainActivity.kt
> +                    val itemsBookedTime = listOf(
I will still have to convert it into a float because even the library use floats to display the graph

2023-06-12 11:52 UTC, kamdaou-amalitech commented on ui/admin/src/main/java/com/amalitech/admin/components/BarGraph.kt
> +    roomNameColor: Color
The items param is an instance of a data class that should have all the needed information. I will convert the data provided by the API into it

2023-06-12 11:53 UTC, kamdaou-amalitech commented on ui/admin/src/main/java/com/amalitech/admin/components/BarGraph.kt
> +        Box(
ok

2023-06-12 15:10 UTC, merged