Created reusable codes in authentication module
AmaliTech-Training-Rw/Meeting-Room-booking-App pull request #29
Opened 2023-06-07 07:58 UTC by kamdaou-amalitech

Added classes and functions that can be reused across the authentication module

2023-06-07 20:14 UTC, esthcarelle commented
Conflicts

2023-06-07 20:15 UTC, esthcarelle approved these changes

2023-06-08 21:26 UTC, esthcarelle commented
Conflicts please

2023-06-09 07:57 UTC, kamdaou-amalitech commented
@esthcarelle it's done

2023-06-09 12:48 UTC, bensek requested changes

2023-06-09 12:48 UTC, bensek commented on ui/onboarding/src/main/java/com/amalitech/onboarding/components/AuthenticationBasedUiState.kt
> +data class AuthenticationBasedUiState(
Make this a sealed class that is accessible globally. It should have 3 children Loading, Success and Error. Use this to update the UI instead of this class. It won't be necessary.

2023-06-09 12:48 UTC, bensek commented on ui/onboarding/src/main/java/com/amalitech/onboarding/forgot_password/ForgotPasswordViewModel.kt
> +) : ViewModel(), AuthenticationBaseViewModel {
Change the BaseViewModel to a class that inherits from the ViewModel and remove this ViewModel() from this line.

2023-06-09 12:48 UTC, bensek commented on ui/onboarding/src/main/java/com/amalitech/onboarding/forgot_password/ForgotPasswordViewModel.kt
> +    override var job: Job? = null
Why are you creating this job?

2023-06-09 12:55 UTC, kamdaou-amalitech commented on ui/onboarding/src/main/java/com/amalitech/onboarding/forgot_password/ForgotPasswordViewModel.kt
> +    override var job: Job? = null
To avoid having several API calls triggered by the user. For example, on the login screen, they can click twice or more on the login button, and without the job, we will call the login use case as many times as they click on the button.

2023-06-09 12:56 UTC, kamdaou-amalitech commented on ui/onboarding/src/main/java/com/amalitech/onboarding/components/AuthenticationBasedUiState.kt
> +data class AuthenticationBasedUiState(
Ok

2023-06-09 12:56 UTC, kamdaou-amalitech commented on ui/onboarding/src/main/java/com/amalitech/onboarding/forgot_password/ForgotPasswordViewModel.kt
> +) : ViewModel(), AuthenticationBaseViewModel {
Ok

2023-06-12 10:36 UTC, kamdaou-amalitech commented
@bensek I have updated the codes

2023-06-12 11:32 UTC, bensek commented on core_ui/src/main/java/com/amalitech/core_ui/util/UiState.kt
> +sealed class UiState<T> {
Could you pass the parameters via UiState instead of the data classes

2023-06-12 11:33 UTC, bensek commented on core_ui/src/main/java/com/amalitech/core_ui/util/UiState.kt
> +sealed class UiState<T> {
Could you pass the parameters via UiState instead of the data classes

2023-06-12 11:42 UTC, bensek approved these changes

2023-06-13 07:18 UTC, kamdaou-amalitech commented
@esthcarelle conflicts are resolved

2023-06-13 10:31 UTC, merged