Created backup branch for BMR30
AmaliTech-Training-Rw/Meeting-Room-booking-App pull request #33
Opened 2023-06-08 10:13 UTC by kclaudeeager

2023-06-08 21:20 UTC, esthcarelle requested changes

2023-06-08 21:20 UTC, esthcarelle commented on ui/swip_animation/src/main/java/com/amalitech/swip_animation/SwipeableCardSideContents.kt
> +import androidx.compose.foundation.shape.RoundedCornerShape
Can you please format the codes?

2023-06-08 21:20 UTC, esthcarelle commented
@kclaudeeager Screenshots please

2023-06-09 08:44 UTC, kclaudeeager commented
> @kclaudeeager Screenshots please

How do I do it? can I add a file in the commits?

2023-06-09 12:45 UTC, esthcarelle commented
@kclaudeeager you can add an image file in the description of the PR

2023-06-09 17:17 UTC, kclaudeeager commented
https://github.com/AmaliTech-Training-Rw/Meeting-Room-booking-App/assets/71407602/04ec92da-6c88-49dc-90b3-4a9e42013668

this is the screen recording of swiping animation

2023-06-12 10:46 UTC, esthcarelle approved these changes

2023-06-15 11:15 UTC, bensek requested changes

2023-06-15 11:15 UTC, bensek commented on ui/swip_animation/src/main/java/com/amalitech/swip_animation/SwipeableCardSideContents.kt
> +        Box(modifier = Modifier.fillMaxHeight()) {
I don't see the need of this Box

2023-06-15 11:15 UTC, bensek commented on ui/swip_animation/src/main/java/com/amalitech/swip_animation/util/SwipeDirection.kt
> +    None, Left, Right
Make these Capital Letters NONE, LEFT, RIGHT

2023-06-15 11:15 UTC, bensek commented on app/build.gradle.kts
> +    implementation(project(Modules.uiSwipe))
We don't need a separate module for this. Use the coreUI module and delete this you have added.

2023-06-22 08:47 UTC, bensek approved these changes

2023-06-22 10:38 UTC, merged