UI fixes on the Onboarding Screens
AmaliTech-Training-Rw/Meeting-Room-booking-App pull request #34
Opened 2023-06-08 10:50 UTC by kamdaou-amalitech

2023-06-08 10:54 UTC, bensek approved these changes
Great

2023-06-08 21:17 UTC, esthcarelle requested changes

2023-06-08 21:17 UTC, esthcarelle commented on ui/onboarding/src/main/java/com/amalitech/onboarding/OnboardingScreen.kt
> +        if (selectedIndex != 3) {
We should not have the 3 hard coded please, try something like this if  selectedIndex != arraySize.length - 1 show the sliding Dot else show the default button

2023-06-08 21:17 UTC, esthcarelle commented on ui/onboarding/src/main/java/com/amalitech/onboarding/components/SlidingDots.kt
>          (0..3).forEach {
Can we avoid having this 3 hard coded, let s pass it as argument

2023-06-09 07:18 UTC, kamdaou-amalitech commented on ui/onboarding/src/main/java/com/amalitech/onboarding/components/SlidingDots.kt
>          (0..3).forEach {
Ok

2023-06-12 10:47 UTC, esthcarelle approved these changes

2023-06-12 10:48 UTC, esthcarelle commented
@kamdaou-amalitech could you please remove this  OnboardingScreen {

                } in MainActivity before I merge it

2023-06-12 10:59 UTC, kamdaou-amalitech commented
@esthcarelle it's done
I have also put the badge on the icon in the bottom nav bar as requested by Evans
![Screenshot_20230612_125916_com amalitech bookmeetingroom production debug](https://github.com/AmaliTech-Training-Rw/Meeting-Room-booking-App/assets/132997531/d48f7283-9087-4125-ab4d-fe82e3eeb51f)

2023-06-12 11:11 UTC, merged