Added search icon in the top app bar
AmaliTech-Training-Rw/Meeting-Room-booking-App pull request #39
Opened 2023-06-13 14:41 UTC by kamdaou-amalitech

Added search icon
Search text field is opened when we click on the Search Icon

2023-06-14 19:37 UTC, esthcarelle requested changes

2023-06-14 19:37 UTC, esthcarelle commented on app/src/main/java/com/amalitech/bookmeetingroom/MainActivity.kt
> +                    Text(text = "Test", modifier = Modifier.padding(it))
@kamdaou-amalitech I created the DeugScreen for you guys to be able to test in the MainActivity

2023-06-14 19:37 UTC, esthcarelle commented on app/src/main/java/com/amalitech/bookmeetingroom/MainActivity.kt
> +                        BookMeetingTopAppBar(
You can add a top app bar button in the debug screen

2023-06-14 19:37 UTC, esthcarelle commented on core_ui/src/main/java/com/amalitech/core_ui/components/BookMeetingTopAppBar.kt
> +//                || appState.currentDestination?.route == NavigationItem.BookingHistory.route
I guess this need to be removed

2023-06-14 19:37 UTC, esthcarelle commented on core_ui/src/main/java/com/amalitech/core_ui/components/BookMeetingTopAppBar.kt
> +                IconButton(onClick = { isSearching = true }) {
Can we have this extracted in its own composable?

2023-06-14 19:37 UTC, esthcarelle commented on core_ui/src/main/java/com/amalitech/core_ui/components/BookMeetingTopAppBar.kt
> +                        onSearchQueryChange(it)
Can you rename the it and make it query?

2023-06-14 21:44 UTC, ma-za-kpe reviewed
The search feature only appears in the user composable, according to the figma designs.

2023-06-15 11:26 UTC, bensek requested changes

2023-06-15 11:26 UTC, bensek commented on core_ui/src/main/java/com/amalitech/core_ui/ui/BookMeetingRoomApp.kt
> +                BookMeetingTopAppBar(appState, title, "search", {}) {}
Look into adding the toolbar actions dynamically depending on the screen you are on.

2023-06-16 14:19 UTC, esthcarelle requested changes

2023-06-16 14:19 UTC, esthcarelle commented on core_ui/src/main/java/com/amalitech/core_ui/components/BookMeetingTopAppBar.kt
> +        mutableStateOf(false)
could you please pass this isSearchTextField as a parameter please?

2023-06-16 15:17 UTC, esthcarelle approved these changes

2023-06-22 08:59 UTC, bensek commented on core_ui/src/main/java/com/amalitech/core_ui/components/BookMeetingTopAppBar.kt
> +            SearchIcon(
This will be shown on all toolbars which we don't want.

2023-06-25 12:21 UTC, kamdaou-amalitech commented on core_ui/src/main/java/com/amalitech/core_ui/components/BookMeetingTopAppBar.kt
> +            SearchIcon(
In the navigation graph, we can add these 3 variables: searchQuery, onSearchQueryChange, and onClick to specify that the screen should have a topAppBar with a search icon. Please refer to `app/src/main/java/com/amalitech/bookmeetingroom/navigation/DebugNavGraph.kt` to see how I used it. These 3 variables should be provided by the ViewModel in charge of the called screen composable

2023-06-25 12:22 UTC, kamdaou-amalitech commented on core_ui/src/main/java/com/amalitech/core_ui/components/BookMeetingTopAppBar.kt
> +            SearchIcon(
Is it still not dynamic enough?

2023-06-27 14:03 UTC, bensek approved these changes

2023-06-29 10:42 UTC, esthcarelle commented
conflicts

2023-06-29 10:51 UTC, kamdaou-amalitech commented
@esthcarelle resolved

2023-06-30 16:16 UTC, merged