Renamed AuthenticationBaseViewModel
AmaliTech-Training-Rw/Meeting-Room-booking-App pull request #40
Opened 2023-06-15 13:28 UTC by kamdaou-amalitech

Renamed AuthenticationBaseViewModel

2023-06-16 12:34 UTC, esthcarelle approved these changes

2023-06-22 09:38 UTC, bensek requested changes

2023-06-22 09:38 UTC, bensek commented on core_ui/src/main/java/com/amalitech/core_ui/util/BaseViewModel.kt
> +    val baseResult = privateBaseResult.asStateFlow()
Rename privateBaseResult to _uiStateFlow and baseResult to uiStateFlow.

2023-06-29 07:36 UTC, bensek approved these changes

2023-06-29 10:42 UTC, esthcarelle commented
@kamdaou-amalitech  conflicts

2023-06-29 10:52 UTC, kamdaou-amalitech commented
@esthcarelle resolved

2023-06-30 16:16 UTC, esthcarelle commented
conflicts

2023-07-03 09:35 UTC, esthcarelle commented
@kamdaou-amalitech conflicts please

2023-07-07 09:04 UTC, merged