Fixing develop by removing swipe module leaving it in core_ui instead
AmaliTech-Training-Rw/Meeting-Room-booking-App pull request #42
Opened 2023-06-23 17:04 UTC by kclaudeeager

2023-06-25 18:15 UTC, esthcarelle requested changes

2023-06-25 18:15 UTC, esthcarelle commented on app/build.gradle.kts
> +            proguardFiles(
This should not be removed please

2023-06-27 14:32 UTC, bensek commented on app/build.gradle.kts
> +    id("com.google.firebase.appdistribution")
Format these

2023-06-27 14:33 UTC, bensek commented on app/build.gradle.kts
>      implementation(AndroidX.coreKtx)
Add back these lines. This change was not necessary.

2023-06-29 07:30 UTC, bensek commented on app/build.gradle.kts
> +    id("com.google.firebase.appdistribution")
Please fix this and add back the spaces after id, it is going to cause conflicts to other people unnecessarily @kclaudeeager

2023-06-29 13:07 UTC, kclaudeeager commented on app/build.gradle.kts
> +    id("com.google.firebase.appdistribution")
done

2023-06-30 07:13 UTC, bensek approved these changes

2023-06-30 16:15 UTC, esthcarelle approved these changes

2023-06-30 16:16 UTC, merged