bmr55 Book room screen
AmaliTech-Training-Rw/Meeting-Room-booking-App pull request #45
Opened 2023-07-07 11:22 UTC by kamdaou-amalitech

Added Book Room screen with business logic and unit tests

https://github.com/AmaliTech-Training-Rw/Meeting-Room-booking-App/assets/132997531/d2c77125-6327-4bf4-88a5-4da821a37ccd

https://github.com/AmaliTech-Training-Rw/Meeting-Room-booking-App/assets/132997531/957f361e-22e6-4e9c-abd9-50b1e8b32df9

2023-07-07 15:52 UTC, kamdaou-amalitech commented
https://github.com/AmaliTech-Training-Rw/Meeting-Room-booking-App/assets/132997531/a5ad3e0d-94b7-4011-b00b-2bd6e0375fa3

2023-07-07 18:04 UTC, bensek requested changes

2023-07-09 15:29 UTC, esthcarelle requested changes

2023-07-09 15:29 UTC, esthcarelle commented on ui/home/src/main/java/com/amalitech/home/book_room/BookRoomViewModel.kt
> +        if (job?.isActive == true)
This function is quite big, could you consider refactoring this into smaller functions?

2023-07-09 15:29 UTC, esthcarelle commented on ui/home/src/main/java/com/amalitech/home/book_room/components/SelectDateBox.kt
> +            .clip(RoundedCornerShape(spacing.spaceExtraSmall))
could you use the parameter shape instead of this?

2023-07-09 15:29 UTC, esthcarelle commented on ui/home/src/main/java/com/amalitech/home/book_room/components/TimeSelector.kt
> +        LazyVerticalGrid(
You should use LazyColumn if it s a single column

2023-07-10 07:24 UTC, kamdaou-amalitech commented on ui/home/build.gradle.kts
> +    "implementation"(Coil.coilCompose)
I did it because Coil is not used in the onboarding module. Should I add it to the base-compose-module?

2023-07-10 07:28 UTC, kamdaou-amalitech commented on domain/home/src/main/java/com/amalitech/home/book_room/model/BookableRoom.kt
> +data class BookableRoom(
I will rename it. But I use bookings to check available time slots. How will I do it if I remove bookings?

2023-07-10 09:57 UTC, kamdaou-amalitech commented on ui/home/src/main/java/com/amalitech/home/book_room/components/TimeSelector.kt
> +        LazyVerticalGrid(
It's a grid as in the image below
![available_times](https://github.com/AmaliTech-Training-Rw/Meeting-Room-booking-App/assets/132997531/acb3a32b-3d09-4518-9585-5baf97c3397f)

2023-07-11 15:43 UTC, bensek requested changes

2023-07-11 15:43 UTC, bensek commented on domain/home/src/main/java/com/amalitech/home/book_room/use_case/GetBookableRoom.kt
> +class GetBookableRoom {
This was not resolved yet

2023-07-11 15:43 UTC, bensek commented on domain/room/src/main/java/com/amalitech/room/di/domainRoomModule.kt
> +        com.amalitech.room.book_room.use_case.GetBookableRoomUseCase()
Refactor this and remove the package name

2023-07-11 16:04 UTC, bensek requested changes

2023-07-12 11:22 UTC, esthcarelle approved these changes

2023-07-12 16:27 UTC, kamdaou-amalitech commented
@bensek Please check

2023-07-24 11:15 UTC, bensek approved these changes

2023-07-24 11:16 UTC, esthcarelle commented
@kamdaou-amalitech a lot of conflicts

2023-07-27 13:46 UTC, merged