BMR 51, 52, 53, 54 My Bookings screen
AmaliTech-Training-Rw/Meeting-Room-booking-App pull request #47
Opened 2023-07-11 13:20 UTC by kamdaou-amalitech

Implemented reusable composable
Implemented Booking screen
Unit tested the ViewModel

2023-07-11 16:14 UTC, bensek commented on ui/booking/src/main/java/com/amalitech/booking/BookingScreen.kt
> +                BookingAppTab(
Do we have to scroll the Tabs as well?

2023-07-12 12:42 UTC, esthcarelle commented
@kamdaou-amalitech I thought the colors were replaced by Maku?It looks like we still have the wrong ones

2023-07-12 12:53 UTC, esthcarelle requested changes

2023-07-12 12:53 UTC, esthcarelle commented on ui/booking/src/main/java/com/amalitech/booking/BookingViewModel.kt
> +                    UiState.Success(data = BookingUiState(response.data!!))
Can you please remove this !! and replace it with proper null handling?

2023-07-12 12:53 UTC, esthcarelle commented on ui/booking/src/test/java/com/amalitech/booking/BookingViewModelTest.kt
> +    fun `ensures fetchBookings update on success`() {
can you also add the  case when the list is empty, because in that case we would have to show  "No items found" message and I don t think that has been implemented

2023-07-12 12:56 UTC, esthcarelle requested changes

2023-07-12 12:56 UTC, esthcarelle commented on core_ui/src/main/java/com/amalitech/core_ui/components/BookingAppTab.kt
> +    object ActiveBookings: Tab(UiText.StringResource(R.string.active))
Why do we have these 4 together?They re from different screens right?

2023-07-12 13:34 UTC, kamdaou-amalitech commented on ui/booking/src/test/java/com/amalitech/booking/BookingViewModelTest.kt
> +    fun `ensures fetchBookings update on success`() {
Ok, I will implement it.

2023-07-12 13:35 UTC, esthcarelle commented on ui/booking/src/main/java/com/amalitech/booking/BookingViewModel.kt
> +                    UiState.Success(data = BookingUiState(response.data!!))
You can replace it with proper null handling either ?. , or let but not using "!!" because that might cause a null pointer exception and a crash in the future

2023-07-12 13:40 UTC, kamdaou-amalitech commented on ui/booking/src/main/java/com/amalitech/booking/BookingViewModel.kt
> +                    UiState.Success(data = BookingUiState(response.data!!))
Ok, let me create a variable to hold the value of `result.data` and then check the nullability of the variable. It will remove the warning

2023-07-12 13:50 UTC, kamdaou-amalitech commented on core_ui/src/main/java/com/amalitech/core_ui/components/BookingAppTab.kt
> +    object ActiveBookings: Tab(UiText.StringResource(R.string.active))
They are used in different screens but all inherit from the Tab sealed class, which is the type of the parameter tab of the TabItem component. To differentiate them, I create lists differently for every tab. If you don't want me to have them all in the same class, I can use a generic type and have two sealed classes. Can I implement it this way or do you suggest anything else?

2023-07-12 14:05 UTC, kamdaou-amalitech commented on ui/booking/src/test/java/com/amalitech/booking/BookingViewModelTest.kt
> +    fun `ensures fetchBookings update on success`() {
But do I need to add a test case for that? I think we can directly display the text or a list of items depending on the data provided to the screen composable without involving the ViewModel. What do you think?

2023-07-12 14:14 UTC, kamdaou-amalitech commented
I have updated the Ui @bensek @esthcarelle 

https://github.com/AmaliTech-Training-Rw/Meeting-Room-booking-App/assets/132997531/6f18659b-4f6b-4a1d-9b22-56426a5e8aaf

2023-07-14 10:30 UTC, esthcarelle commented on ui/booking/src/test/java/com/amalitech/booking/BookingViewModelTest.kt
> +    fun `ensures fetchBookings update on success`() {
yes you need to add it

2023-07-15 06:24 UTC, kamdaou-amalitech commented on ui/booking/src/test/java/com/amalitech/booking/BookingViewModelTest.kt
> +    fun `ensures fetchBookings update on success`() {
Please, check the code in the ViewModel. I am not doing anything special like sending an event or changing states for this case. So, I think having a test case for it is not necessary. Otherwise, can you give me what we need to test exactly (like the expected behavior from the ViewModel in that case) so that I write the test?

2023-07-17 09:19 UTC, esthcarelle commented on ui/booking/src/test/java/com/amalitech/booking/BookingViewModelTest.kt
> +    fun `ensures fetchBookings update on success`() {
we are expected to get an empty array(size 0)

2023-07-18 12:35 UTC, bensek approved these changes

2023-07-19 10:15 UTC, kamdaou-amalitech commented on ui/booking/src/test/java/com/amalitech/booking/BookingViewModelTest.kt
> +    fun `ensures fetchBookings update on success`() {
@esthcarelle I updated the code

2023-07-23 20:51 UTC, esthcarelle approved these changes

2023-07-23 20:51 UTC, merged