Removed Debug Screen and added navigation button
AmaliTech-Training-Rw/Meeting-Room-booking-App pull request #50
Opened 2023-07-13 11:09 UTC by kamdaou49

Removed Debug Screen and added navigation button 
There is no profile screen, so I have just found a way to put the button. The UI will be improved by the one who will do the profile screens.

https://github.com/AmaliTech-Training-Rw/Meeting-Room-booking-App/assets/132997531/70c8bf74-b642-4568-a504-6e57d9b9768c

2023-07-15 15:28 UTC, esthcarelle requested changes

2023-07-15 15:28 UTC, esthcarelle commented on app/src/main/java/com/amalitech/bookmeetingroom/navigation/AppNavHost.kt
> +        mainNavGraph(navController)
We should find a way of combining these two in one graph

2023-07-15 15:28 UTC, esthcarelle commented on app/src/main/java/com/amalitech/bookmeetingroom/navigation/AppNavHost.kt
> +                        navController.navigate(Route.DASHBOARD_SCREENS) {
Why do we have this button in this PR?

2023-07-15 15:28 UTC, esthcarelle commented on app/src/main/java/com/amalitech/bookmeetingroom/navigation/BookMeetingRoomNavHost.kt
> +            TestScreen("This is ${NavigationItem.Home.title}", innerPadding)
Why did we remove the appState argument?

2023-07-17 09:08 UTC, kamdaou-amalitech commented on app/src/main/java/com/amalitech/bookmeetingroom/navigation/AppNavHost.kt
> +        mainNavGraph(navController)
Ok

2023-07-17 10:25 UTC, kamdaou-amalitech commented on app/src/main/java/com/amalitech/bookmeetingroom/navigation/AppNavHost.kt
> +                        navController.navigate(Route.DASHBOARD_SCREENS) {
To make sure we can navigate back to the home screen. And since the buttons are supposed to be on the profile screen, I put them there for now until we have the profile screen. Isn't it their place?

2023-07-24 11:33 UTC, bensek approved these changes

2023-07-28 11:02 UTC, esthcarelle commented
@kamdaou do you think this should be merged before the profile screen or after?(for testing purposes)

2023-07-28 11:02 UTC, esthcarelle commented
and you also have conflicts

2023-07-28 11:10 UTC, kamdaou49 commented
I did not add the profile screen into the debug navigation graph, so there is no conflicts between the two. But let's merge this first.

2023-07-28 15:01 UTC, esthcarelle approved these changes

2023-07-28 15:02 UTC, merged