bmr42 Profile screen
AmaliTech-Training-Rw/Meeting-Room-booking-App pull request #52
Opened 2023-07-14 18:24 UTC by kamdaou-amalitech

Added profile screen
Added room database, saving profile information every time the user logged in
[profile screen.webm](https://github.com/AmaliTech-Training-Rw/Meeting-Room-booking-App/assets/132997531/0d99a26f-f66b-40d4-8fb4-94436930b59e)

2023-07-15 10:02 UTC, esthcarelle commented
@kamdaou-amalitech pipelines are not passing

2023-07-15 12:52 UTC, kamdaou commented
Help me to find out what makes it fail, please. All my tests are passing locally.

2023-07-19 12:59 UTC, esthcarelle commented
Why doesn't it look like the mockup?

2023-07-20 08:53 UTC, kamdaou-amalitech commented
![image](https://github.com/AmaliTech-Training-Rw/Meeting-Room-booking-App/assets/132997531/26893941-4158-4d77-abb3-368800d0a08c)

2023-07-22 20:38 UTC, esthcarelle requested changes

2023-07-22 20:38 UTC, esthcarelle commented on buildSrc/src/main/java/Room.kt
> +    private const val version = "2.5.2"
why did we update the room version?

2023-07-22 20:38 UTC, esthcarelle commented on app/src/main/java/com/amalitech/bookmeetingroom/navigation/AppNavHost.kt
> +                profileViewModel.updateAdminUserScreen(false)
Why do we have the admin toggle here?

2023-07-22 20:38 UTC, esthcarelle commented on app/src/main/java/com/amalitech/bookmeetingroom/navigation/AppNavHost.kt
> +                            popUpTo(Route.DASHBOARD_SCREENS) {
these 2 navigate to the same screens

2023-07-24 13:52 UTC, kamdaou-amalitech commented on buildSrc/src/main/java/Room.kt
> +    private const val version = "2.5.2"
We updated the room version because this version has fixed some issues (according to the release note), and it doesn't harm as there is no compatibility issue.

2023-07-24 14:04 UTC, kamdaou-amalitech commented on app/src/main/java/com/amalitech/bookmeetingroom/navigation/AppNavHost.kt
> +                            popUpTo(Route.DASHBOARD_SCREENS) {
Do you want them to navigate to the same screen? Because right now, the routes are different

2023-07-28 11:00 UTC, esthcarelle approved these changes

2023-07-28 11:00 UTC, esthcarelle commented
@kamdaou could you please resolve these conflicts?

2023-07-28 13:24 UTC, bensek requested changes

2023-07-28 13:24 UTC, bensek commented on ui/user/src/main/java/com/amalitech/user/profile/ProfileScreen.kt
> +    LaunchedEffect(key1 = uiState) {
Why do we need this LaunchedEffect?

2023-08-03 15:39 UTC, kamdaou commented on ui/user/src/main/java/com/amalitech/user/profile/ProfileScreen.kt
> +    var user: UserDto? by remember {
In one of my previous PRs, I had different data classes for different layers and you said I could just have one since they all hold the same data. That's why I am using the Dto data class in all my layers. It's in the domain layer so it can be shared.

2023-08-03 15:48 UTC, kamdaou commented on ui/user/src/main/java/com/amalitech/user/profile/ProfileScreen.kt
> +                        model = user!!.profileImgUrl,
Ok

2023-08-09 09:15 UTC, bensek approved these changes

2023-08-09 16:15 UTC, merged