User item: 34 => Maku
AmaliTech-Training-Rw/Meeting-Room-booking-App pull request #54
Opened 2023-07-26 12:59 UTC by ma-za-kpe

# TASKS
1. Add the user-item composable, with a swipe gesture
2. Add extra code (modules, repo, etc), in preparation from the full users screen. Ideally, this code should not exist in the branch, but I got carried away.

# DEMO
## Single user
https://github.com/AmaliTech-Training-Rw/Meeting-Room-booking-App/assets/28810111/7b077004-cea6-496a-8fe1-2318534320c5

## List of users
![users](https://github.com/AmaliTech-Training-Rw/Meeting-Room-booking-App/assets/28810111/d526ab09-2854-4d79-87d9-72a4fe8c47da)

## Users With bottom sheet open
![usersheet](https://github.com/AmaliTech-Training-Rw/Meeting-Room-booking-App/assets/28810111/a806eeaf-ad78-4a12-8bcd-0e0e1050125c)

## Bottomsheet
![sheet](https://github.com/AmaliTech-Training-Rw/Meeting-Room-booking-App/assets/28810111/899d76f5-5472-4bce-be3a-23c283ff64d4)

2023-07-28 10:58 UTC, esthcarelle requested changes

2023-07-28 10:58 UTC, esthcarelle commented on core_ui/src/main/java/com/amalitech/core_ui/swipe_animation/SwipeAction.kt
> +fun SwipeAction(
Why does it look like this was added? Couldn't we reuse the one that is already implemented?

2023-07-28 10:58 UTC, esthcarelle commented on ui/rooms/src/main/java/com/amalitech/rooms/components/RoomCard.kt
> -private fun SwipeAction(
This looks like it was moved?Is there any specific reason for this?

2023-07-28 10:58 UTC, esthcarelle commented on ui/user/src/main/java/com/amalitech/user/UserScreen.kt
> +    val cardBg = if (isRightVisible) {
I think it would be better to pass this cardBg as parameters since we might need it elsewhere with a different background

2023-07-28 10:58 UTC, esthcarelle commented on ui/user/src/main/java/com/amalitech/user/UserScreen.kt
> +            painter = painterResource(R.drawable.user),
We will be getting user image from the backend , so we should support url as image url

2023-07-28 10:58 UTC, esthcarelle commented on ui/user/src/main/java/com/amalitech/user/UserScreen.kt
> +    }
We should also have a list here inside of UserScreen (List of userItems)

2023-07-28 11:22 UTC, ma-za-kpe commented on core_ui/src/main/java/com/amalitech/core_ui/swipe_animation/SwipeAction.kt
> +fun SwipeAction(
I reused it, so I moved it to the core_ui module, that's why it looks added.

2023-07-28 11:23 UTC, ma-za-kpe commented on ui/user/src/main/java/com/amalitech/user/UserScreen.kt
> +    val cardBg = if (isRightVisible) {
But, this bg is specific for only the user item, we arent sharing the user-item anywhere. PTAL

2023-07-28 11:24 UTC, ma-za-kpe commented on ui/user/src/main/java/com/amalitech/user/UserScreen.kt
> +            painter = painterResource(R.drawable.user),
Yes, I left that there by design as a placeholder. If you check the user Item you'll notice a URL string for the user.

2023-07-28 11:26 UTC, ma-za-kpe commented on ui/user/src/main/java/com/amalitech/user/UserScreen.kt
> +    }
Yes, however this is task 34 (https://amali-tech.atlassian.net/browse/BMR-34), which only required the user-item composable. My next task,  Users screen is where i shall implement a list of users.

2023-07-28 11:26 UTC, ma-za-kpe commented on ui/user/src/main/java/com/amalitech/user/UserScreen.kt
> +    }
Or should i go ahead a combine the two tasks?

2023-07-28 11:51 UTC, ma-za-kpe commented on ui/rooms/src/main/java/com/amalitech/rooms/components/RoomCard.kt
> -private fun SwipeAction(
Im reusing the same code in the users item, as its also being used in the room item. PTAL

2023-07-28 13:29 UTC, bensek commented on ui/user/src/main/java/com/amalitech/user/UserScreen.kt
> +    }
I side with combining the task since they are closely related

2023-07-28 13:35 UTC, bensek requested changes

2023-07-28 13:35 UTC, bensek commented on ui/user/src/main/java/com/amalitech/user/domain/usecases/GetUsers.kt
> +class GetUsers constructor(
We agreed with Cadet to add the suffix UseCase to all use cases. 
Also UseCases live in the domain layer

2023-07-28 15:00 UTC, esthcarelle commented on ui/user/src/main/java/com/amalitech/user/UserScreen.kt
> +    }
sure

2023-07-28 19:07 UTC, ma-za-kpe commented on ui/user/src/main/java/com/amalitech/user/domain/usecases/GetUsers.kt
> +class GetUsers constructor(
Done, PTAL

2023-07-29 19:40 UTC, esthcarelle approved these changes

2023-08-04 19:12 UTC, esthcarelle approved these changes

2023-08-09 09:10 UTC, merged