BMR-57:  Invite Screen LISt -> MAKU
AmaliTech-Training-Rw/Meeting-Room-booking-App pull request #57
Opened 2023-08-15 07:58 UTC by ma-za-kpe

- Add invite list
- Add Invite modules
- Add repo implementations

## DEMO
![invite](https://github.com/AmaliTech-Training-Rw/Meeting-Room-booking-App/assets/28810111/40fa0190-b824-450b-ac90-3b70511b5e72)

2023-08-15 08:12 UTC, ma-za-kpe commented
Ill just work on the add invite feature in the same PR @esthcarelle

2023-08-15 14:34 UTC, esthcarelle approved these changes

2023-08-18 07:02 UTC, bensek approved these changes

2023-08-18 07:25 UTC, kamdaou requested changes

2023-08-18 07:25 UTC, kamdaou commented on app/src/main/java/com/amalitech/bookmeetingroom/navigation/BookMeetingRoomApp.kt
> +                        when(destination.title) {
Please, use the AppBarState class to add a floating action button as the one on the users' screen in the develop branch. From there, you can add the title displayed on the top app bar, action buttons, and a navigation button if there is one on the top app bar. You can also add a floating action button. 
Kindly check out the code in the develop branch.

2023-08-18 07:40 UTC, Evansmbongo commented
@ma-za-kpe the Invitations screen does not have the plus icon on the figma design. It should not have the hamburger icon since it will be on the normal user screen and not the admin. The page title "invitations" should be "Invitations".

2023-08-22 11:10 UTC, ma-za-kpe commented on app/src/main/java/com/amalitech/bookmeetingroom/navigation/BookMeetingRoomApp.kt
> +                        when(destination.title) {
Im removing the add invite feature, since we already have it on the admin side. So  ill not be using the AppBarState at this time

2023-08-22 11:51 UTC, Evansmbongo approved these changes

2023-08-23 10:43 UTC, kamdaou approved these changes

2023-08-23 13:23 UTC, ma-za-kpe commented
@kamdaou  and @esthcarelle , pushed as discussed in the meeting. PTAL

2023-08-23 13:37 UTC, merged